[phases.setup]
nixPkgs = ["python311", "playwright-driver"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt", "python -m playwright install --with-deps chromium"]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
